import MainLayout from '../../components/MainLayout';
import Head from 'next/head';
import Card from '../../components/Card';
import { Spinner } from '../../components/Spinner';
import { db } from '../../context/firebaseContext';
import { collection, getDocs } from 'firebase/firestore/lite';
import { useGoodsContext } from '../../context/contextGoods';
import useSWR from 'swr';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import Toolbar from '../../components/Toolbar';
import Category from '../../components/Category';
import Doubleicon from '../../components/DoubleIcon';
function Hoodie({ goodList }) {
  const goodClient = JSON.parse(goodList);

  const { state, dispatch } = useGoodsContext();

  useEffect(() => {
    if (state.hoodie.length === 0) {
      dispatch({ type: 'ADD HOODIE', payload: [...goodClient] });
    }
  }, []);
  const getGoods = async () => {
    // dispatch({ type: 'ADD HOODIE', payload: [...goodClient] });
  };
  const { data, isValidating } = useSWR('hoodie', getGoods, {
    fallbackData: goodClient,
  });

  const add = ({ id, title, description, price, urlArr, color }) => {
    const copyGood = state.hoodie.slice();
    copyGood.map((item) => {
      if (item.id === id) {
        item.active = 'active';
      }
    });

    dispatch({ type: 'ADD HOODIE', payload: [...copyGood] });
    dispatch({
      type: 'ADD TO CART',
      payload: {
        id,
        title,
        price,
        urlArr,
        color,
        sum: price * 5,
        cnt: 5,
        active: 'active',
      },
    });
  };

  const [show, setShow] = useState(false);
  const showTwoGood = () => {
    setShow(false);
  };
  const showOneGood = () => {
    setShow(true);
  };

  return (
    <MainLayout>
      <Head>
        {' '}
        <title>худi</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {isValidating ? (
        <>
          <Spinner></Spinner>
          {state.hoodie.map((obj, i) => {
            return (
              <div className="productCard_block-katalog" key={i}>
                <div>
                  <Image
                    alt={'hoodie'}
                    width={300}
                    height={400}
                    src={
                      'https://firebasestorage.googleapis.com/v0/b/b-sportwear-shop.appspot.com/o/no_image.png?alt=media&token=47b4ea63-cf4a-4b67-9fa7-8e8004f97505'
                    }></Image>
                  <div className="bottom-subtitle">
                    <button className="button button-default-white">...</button>
                  </div>
                </div>
              </div>
            );
          })}
        </>
      ) : (
        <>
          <h1 className="title-product-block">худi</h1>
          <div className="toolbar toolbar-products">
            <h3 className="title-category">категорii</h3>
            <Doubleicon show={show} showTwoGood={showTwoGood} showOneGood={showOneGood} />
            <div className="cnt-goods">Товарiв:&nbsp;{state.hoodie.length}</div>
            <Toolbar state={state.hoodie} type={'ADD HOODIE'} />
          </div>
          <div className="section-filter-products">
            <div className="section-left">
              <Category cls={'menu-for-page'}></Category>
            </div>
            <div className="section-right">
              {state.hoodie.map((good) => {
                return (
                  <Card
                    add={add}
                    active={good.active}
                    id={good.id}
                    key={good.id}
                    title={good.title}
                    price={good.price}
                    urlArr={good.urlArr}
                    color={good.color}
                    description={good.description}
                    show={show}></Card>
                );
              })}
            </div>
          </div>
        </>
      )}
    </MainLayout>
  );
}
export async function getStaticProps() {
  const docRef = collection(db, 'hoodie');
  const querySnapshot = await getDocs(docRef);
  const goodList = querySnapshot.docs.map((doc) => doc.data());

  return {
    props: { goodList: JSON.stringify(goodList) || null },
  };
}

export default Hoodie;
