import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { useAppContext } from '../../context/firebaseContext';
import MainLayout from '../components/MainLayout';
import Head from 'next/head';
import Card from '../components/Card';
import Loader from '../components/loader';
export default function Pants() {
  const router = useRouter();

  const { loading, good, getGood } = useAppContext();

  useEffect(() => {
    getGood(router.pathname);
  }, []);

  return (
    <MainLayout>
      <Head>
        {' '}
        <title>штаны</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {loading ? (
        <Loader></Loader>
      ) : (
        <>
          <h3 className="title-product-block">штаны</h3>
          {good &&
            good.map((good) => {
              return (
                <Card
                  description={good.description}
                  id={good.id}
                  key={good.id}
                  title={good.title}
                  price={good.price}
                  url={good.url}></Card>
              );
            })}
        </>
      )}
    </MainLayout>
  );
}
