import Head from 'next/head';

import MainLayout from './components/MainLayout';

export default function index(props) {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>home</h1>
    </MainLayout>
  );
}
