import Head from 'next/head';
import { useEffect } from 'react';
import MainLayout from './components/MainLayout';
import Slider from '../context/Slider';

import { useAppContext } from '../context/firebaseContext';
export default function Index(props) {
  const { good, getGood } = useAppContext();
  useEffect(() => {
    console.log(' useEffect redner index', good);
    // getGood('pants');
  }, []);

  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>home</h1>
      <Slider></Slider>
    </MainLayout>
  );
}
