import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { useAppContext } from '../../context/firebaseContext';

import Card from '../../components/Card';
import MainLayout from '../../components/MainLayout';
import { Spinner } from '../../components/Spinner';
import Head from 'next/head';
function Kostums() {
  const router = useRouter();

  const { loading, good, getGood } = useAppContext();
  useEffect(() => {
    getGood(router.pathname);
  }, []);
  console.log('good', good);
  return (
    <MainLayout>
      <Head>
        {' '}
        <title>Костюмы</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {loading ? (
        <Spinner></Spinner>
      ) : (
        <>
          <h2 className="title-product-block">Спортивные костюмы</h2>
          <div className="block-filter"></div>

          {good &&
            good.map((good) => {
              return (
                <Card
                  description={good.description}
                  id={good.id}
                  key={good.id}
                  title={good.title}
                  price={good.price}
                  url={good.url}></Card>
              );
            })}
        </>
      )}
    </MainLayout>
  );
}

// Kostums.getInitialProps = async ({ goods }) => {

// };

export default Kostums;
